name: demos
channels:
  - conda-forge
  - defaults
dependencies:
  - absl-py=2.3.1
  - anyio=4.10.0
  - appnope=0.1.4
  - apricot-select=0.6.1
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - black=25.1.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.3
  - clarabel=0.11.1
  - click=8.2.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cpython=3.12.11
  - cvxpy=1.5.3
  - cvxpy-base=1.5.3
  - cycler=0.12.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - ecos=2.0.14
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - filelock=3.18.0
  - flatbuffers=24.12.23
  - fonttools=4.59.0
  - fqdn=1.5.1
  - fredapi=0.5.2
  - freetype=2.13.3
  - fsspec=2025.7.0
  - gast=0.6.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - google-pasta=0.2.0
  - grpcio=1.67.1
  - h11=0.16.0
  - h2=4.2.0
  - h5py=3.14.0
  - hdf5=1.14.6
  - hpack=4.1.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.5
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - keras=3.10.0
  - khronos-opencl-icd-loader=2024.10.24
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20240722.0
  - libaec=1.1.4
  - libblas=3.9.0
  - libboost=1.88.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libgrpc=1.67.1
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblightgbm=4.6.0
  - liblzma=5.8.1
  - libml_dtypes-headers=0.5.2
  - libmpdec=4.0.0
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libosqp=0.6.3
  - libpng=1.6.50
  - libprotobuf=5.28.3
  - libqdldl=0.1.7
  - libre2-11=2024.07.02
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtensorflow_cc=2.18.0
  - libtensorflow_framework=2.18.0
  - libtiff=4.7.0
  - libtorch=2.6.0
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - lightgbm=4.6.0
  - llvm-openmp=20.1.8
  - llvmlite=0.44.0
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.5
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - mistune=3.1.3
  - ml_dtypes=0.4.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - namex=0.1.0
  - narwhals=2.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - nomkl=1.0
  - nose=1.3.7
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numpy=2.2.6
  - opencl-headers=2025.06.13
  - openjpeg=2.5.3
  - openssl=3.5.2
  - opt_einsum=3.4.0
  - optree=0.17.0
  - osqp=0.6.7.post3
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - parso=0.8.4
  - pathspec=0.12.1
  - patsy=1.0.1
  - pexpect=4.9.0
  - pgmpy=1.0.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.3.8
  - plotly=6.2.0
  - pomegranate=1.0.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - protobuf=5.28.3
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pybind11=3.0.0
  - pybind11-global=3.0.0
  - pycparser=2.22
  - pygments=2.19.2
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyparsing=3.2.3
  - pyro-api=0.1.2
  - pyro-ppl=1.9.1
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-fastjsonschema=2.21.1
  - python-flatbuffers=25.2.10
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytorch=2.6.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qdldl-python=0.1.7.post5
  - qhull=2020.2
  - re2=2024.07.02
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rpds-py=0.27.0
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - scs=3.2.7.post2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.8
  - snappy=1.2.2
  - sniffio=1.3.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - sympy=1.14.0
  - tensorboard=2.18.0
  - tensorboard-data-server=0.7.0
  - tensorflow=2.18.0
  - tensorflow-base=2.18.0
  - tensorflow-estimator=2.18.0
  - termcolor=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250809
  - typing-extensions=4.14.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.2
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - backoff==2.2.1
      - curl-cffi==0.13.0
      - frozendict==2.4.6
      - multitasking==0.0.12
      - myeia==0.4.8
      - peewee==3.18.2
      - websockets==15.0.1
      - yfinance==0.2.65
